// Generated by insterra

module "aws_bucket_sombrero_ini" {
  source  = "upmaru/instellar/aws//modules/bucket"
  version = "0.9.3"

  blueprint  = var.identifier
  identifier = "sombrero-ini"
  region     = var.aws_region
}
