// Generated by insterra

module "instellar_link_sombrero_teh" {
  source  = "upmaru/bootstrap/instellar"
  version = "0.8.1"

  balancer              = module.aws_compute_sombrero_cag.balancer
  bootstrap_node        = module.aws_compute_sombrero_cag.bootstrap_node
  cluster_address       = module.aws_compute_sombrero_cag.cluster_address
  cluster_name          = module.aws_compute_sombrero_cag.identifier
  insterra_component_id = 278
  kit_slug              = "lite"
  nodes                 = module.aws_compute_sombrero_cag.nodes
  password_token        = module.aws_compute_sombrero_cag.trust_token
  provider_name         = "aws"
  region                = var.aws_region

}

module "instellar_link_sombrero_yhx" {
  source  = "upmaru/bootstrap/instellar//modules/service"
  version = "0.8.1"

  certificate = module.aws_database_sombrero_qas.certificate_url
  channels    = ["main", "master"]
  cluster_ids = [
    module.instellar_link_sombrero_teh.cluster_id
  ]
  credential = {
    host     = module.aws_database_sombrero_qas.address
    password = module.aws_database_sombrero_qas.password
    port     = module.aws_database_sombrero_qas.port
    resource = module.aws_database_sombrero_qas.db_name
    username = module.aws_database_sombrero_qas.username
    secure   = true
  }

  driver                = "database/postgresql"
  driver_version        = module.aws_database_sombrero_qas.engine_version
  insterra_component_id = 279
  provider_name         = "aws"
  slug                  = module.aws_database_sombrero_qas.identifier
}

module "instellar_link_sombrero_wyh" {
  source  = "upmaru/bootstrap/instellar//modules/storage"
  version = "0.8.1"

  access_key            = module.aws_storage_sombrero_lum.access_key_id
  bucket                = module.aws_storage_sombrero_lum.name
  host                  = module.aws_storage_sombrero_lum.host
  insterra_component_id = 280
  region                = var.aws_region
  secret_key            = module.aws_storage_sombrero_lum.secret_access_key
}

module "instellar_link_sombrero_jml" {
  source  = "upmaru/bootstrap/instellar//modules/service"
  version = "0.8.1"


  channels = ["main", "master"]
  cluster_ids = [
    module.instellar_link_sombrero_teh.cluster_id
  ]
  credential = {
    host     = module.aws_bucket_sombrero_ini.host
    password = module.aws_bucket_sombrero_ini.secret_access_key
    port     = module.aws_bucket_sombrero_ini.port
    resource = module.aws_bucket_sombrero_ini.region
    username = module.aws_bucket_sombrero_ini.access_key_id
    secure   = true
  }

  driver                = "bucket/aws-s3"
  driver_version        = module.aws_bucket_sombrero_ini.version
  insterra_component_id = 281
  provider_name         = "aws"
  slug                  = module.aws_bucket_sombrero_ini.identifier
}
